version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
    command: npm start
    restart: unless-stopped


networks:
  portfolio-network:
    driver: bridge